version: '3'
services:
  portfolio-website:
    image: ghcr.io/theexeq/portfolio/portfolio-website:latest
    container_name: portfolio-website
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - nginx-router
      
networks:
  nginx-router:
    external: true